# -*- coding: utf-8 -*-
"""Desafio - Visualização de Dados Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vRLnyyDb0bnxVWuXErPT5H_Vx0TdwF7d

## **Desafio - Visualização de Dados Streamlit**

**Aluno:** Romulo Galdino.
"""

# Importando bibliotecas.
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Extração: Coletar dados de uma fonte.

# Lista de URLs dos arquivos CSV

urls = [
    "/content/sample_data/sales_data.csv"
]

# Create a list to store DataFrames
dfs = []

# Iterate through the URLs and read each CSV into a DataFrame
for url in urls:
    df = pd.read_csv(url)  # Assuming your data is in CSV format
    dfs.append(df)

# Concatenate all DataFrames in the list into a single DataFrame
df_final = pd.concat(dfs, ignore_index=True)

# Visualização inicial dos dados com os novos nomes de coluna
print("Visualização inicial dos dados:")
df_final.head()